import Head from 'next/head';
import DashBoard from '../components/DashBoard';
import { useRouter } from 'next/router';
// import { useEffect, useRef } from "react";
//import { CloudIcon } from "@heroicons/react/outline";


// const API_KEY = process.env.API_KEY;

export default function Home() {
     const router = useRouter();
  // const searchInputRef = useRef(null);

  //     const search = (e) => {
  //       e.preventDefault();
  //       const city = searchInputRef.current.value;
  //       if (!city) return;
  //       router.push(`/dash?city=${city}`);
  //     };

  
  // console.log(cityDets,weather)
  return (
    <div>
      <Head>
        <title>{router.query.city} - 4cast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rain.ico" />
      </Head>
      
      {/* <DashBoard cityDets={cityDets} weather={ weather}/>  */}
      <DashBoard/>
      {/* <main>
        <div className="max-w-lg mx-auto my-8 flex flex-col">
          <div className="flex items-center justify-center text-gray-700">
            <h2 className="text-5xl text-center">4cast</h2>
            <CloudIcon className="h-10" />
          </div>
          <div className="w-full text-center my-10">
            <h3 className="m-2">Enter a Location for weather Information</h3>
            <form onSubmit={search}>
              <input
                ref={searchInputRef}
                defaultValue={router.query.city}
                type="text"
                className="h-16 w-9/12 text-center"
              />
            </form>
          </div>
          <Card  cityDets={cityDets} weather={weather}/>
        </div>
      </main> */}
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const data = await fetch(
//       `http://dataservice.accuweather.com/locations/v1/cities/search?apikey=${API_KEY}&q=${context.query.city}`
//   ).then(response =>  response.json())
//     .catch(err => console.log(err));
//   // let dataKey = data.map((item)=>item.Key)
//   let locationData =  data[0]
//   const newData = await fetch(
//     `http://dataservice.accuweather.com/currentconditions/v1/${ locationData.Key}?apikey=${API_KEY}`
//    ).then(response => response.json())
  
//   return {
//     props: {
//       cityDets:locationData,
//       weather:newData
//     }
//   };
// }